"""ORM models for Agent Pipeline (Pipeline 3) output tables.

Each row type corresponds to the output of one sub-agent and maps to
a dedicated ``lp_`` prefixed table.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from learning_platform.infrastructure.persistence.models.base import Base


class KeywordRow(Base):
    """A key term + definition extracted per lesson by KeywordsAgent."""

    __tablename__ = "lp_keywords"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    document_id: Mapped[str] = mapped_column(String(36), nullable=False)
    lesson_id: Mapped[str] = mapped_column(String(36), nullable=False)
    term: Mapped[str] = mapped_column(Text, nullable=False)
    definition: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class SummaryRow(Base):
    """A lesson summary produced by SummariesAgent."""

    __tablename__ = "lp_summaries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    document_id: Mapped[str] = mapped_column(String(36), nullable=False)
    lesson_id: Mapped[str] = mapped_column(String(36), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class QuizQuestionRow(Base):
    """An MCQ quiz question generated by QuizzesAgent.

    ``choices`` stores a JSON-serialised list[str].
    ``correct_index`` is the 0-based index of the correct choice.
    """

    __tablename__ = "lp_quiz_questions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    document_id: Mapped[str] = mapped_column(String(36), nullable=False)
    lesson_id: Mapped[str] = mapped_column(String(36), nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    choices: Mapped[str] = mapped_column(Text, nullable=False)  # JSON array
    correct_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    explanation: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class PracticeQuestionRow(Base):
    """An MCQ practice question generated by PracticeAgent.

    Same schema as QuizQuestionRow; distinguished by table and applied framing.
    """

    __tablename__ = "lp_practice_questions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    document_id: Mapped[str] = mapped_column(String(36), nullable=False)
    lesson_id: Mapped[str] = mapped_column(String(36), nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    choices: Mapped[str] = mapped_column(Text, nullable=False)  # JSON array
    correct_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    explanation: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class AgentFlashcardRow(Base):
    """An AI-generated flashcard seed produced by FlashcardsAgent.

    Stored separately from user-facing FSRS flashcards (``lp_flashcards``).
    """

    __tablename__ = "lp_agent_flashcards"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    document_id: Mapped[str] = mapped_column(String(36), nullable=False)
    lesson_id: Mapped[str] = mapped_column(String(36), nullable=False)
    front: Mapped[str] = mapped_column(Text, nullable=False)
    back: Mapped[str] = mapped_column(Text, nullable=False)
    source_type: Mapped[str] = mapped_column(String(32), nullable=False, default="agent")
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
