"""add learning domain indexes

Revision ID: 38ce77c986ab
Revises: 86e8229cd9b
Create Date: 2026-07-21 15:05:37.860651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ce77c986ab'
down_revision: Union[str, Sequence[str], None] = '86e8229cd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index('idx_lessons_section_id', ['section_id', 'display_order'], unique=False)

    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.create_index('idx_practices_section_id', ['section_id', 'display_order'], unique=False)

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index('idx_quizzes_section_id', ['section_id'], unique=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index('idx_sections_unit_id', ['unit_id'], unique=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index('idx_units_course_id', ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('idx_units_course_id')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index('idx_sections_unit_id')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index('idx_quizzes_section_id')

    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_index('idx_practices_section_id')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index('idx_lessons_section_id')

    # ### end Alembic commands ###
