"""uuid_notes_flashcards_lp_documents_schema_updates

Revision ID: 6352f7c6c312
Revises: a8d9e7c6b5a4
Create Date: 2026-08-04 19:33:19.289132

"""

from typing import Sequence, Union

import sys
from pathlib import Path

# Ensure learning_platform src is importable
_lp_src = str(
    Path(__file__).resolve().parent.parent.parent / "learning_platform" / "src"
)
if _lp_src not in sys.path:
    sys.path.insert(0, _lp_src)

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from learning_platform.infrastructure.persistence.models.base import JsonType

# revision identifiers, used by Alembic.
revision: str = "6352f7c6c312"
down_revision: Union[str, Sequence[str], None] = "a8d9e7c6b5a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course_templates", schema=None) as batch_op:
        batch_op.alter_column(
            "structure",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        )

    with op.batch_alter_table("lp_book_process", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_book_process_document_id"))
        batch_op.drop_index(batch_op.f("ix_lp_book_process_status"))

    with op.batch_alter_table("lp_concept_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_source"))
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_target"))
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_source_concept_id"),
            ["source_concept_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_target_concept_id"),
            ["target_concept_id"],
            unique=False,
        )

    with op.batch_alter_table("lp_documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("metadata", JsonType(), nullable=True))
        batch_op.add_column(sa.Column("nodes", JsonType(), nullable=True))
        batch_op.drop_column("nodes_json")
        batch_op.drop_column("metadata_json")

    with op.batch_alter_table("lp_graph_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_source"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_target"))
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_source_node_id"),
            ["source_node_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_target_node_id"),
            ["target_node_id"],
            unique=False,
        )

    # user_flashcards: drop FKs, drop sequence default, cast columns, set UUID default
    with op.batch_alter_table("user_flashcards", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("user_flashcards_unit_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("user_flashcards_lesson_id_fkey"), type_="foreignkey"
        )
    op.execute("ALTER TABLE user_flashcards ALTER COLUMN id DROP DEFAULT")
    op.execute(
        "ALTER TABLE user_flashcards ALTER COLUMN id TYPE UUID USING gen_random_uuid()"
    )
    op.execute(
        "ALTER TABLE user_flashcards ALTER COLUMN id SET DEFAULT gen_random_uuid()"
    )
    op.execute("ALTER TABLE user_flashcards ALTER COLUMN unit_id DROP DEFAULT")
    op.execute(
        "ALTER TABLE user_flashcards ALTER COLUMN unit_id TYPE UUID USING NULL::uuid"
    )
    op.execute("ALTER TABLE user_flashcards ALTER COLUMN lesson_id DROP DEFAULT")
    op.execute(
        "ALTER TABLE user_flashcards ALTER COLUMN lesson_id TYPE UUID USING NULL::uuid"
    )

    # user_notes: drop FKs, drop sequence default, cast columns, set UUID default
    with op.batch_alter_table("user_notes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("user_notes_unit_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("user_notes_lesson_id_fkey"), type_="foreignkey"
        )
    op.execute("ALTER TABLE user_notes ALTER COLUMN id DROP DEFAULT")
    op.execute(
        "ALTER TABLE user_notes ALTER COLUMN id TYPE UUID USING gen_random_uuid()"
    )
    op.execute("ALTER TABLE user_notes ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.execute("ALTER TABLE user_notes ALTER COLUMN unit_id DROP DEFAULT")
    op.execute("ALTER TABLE user_notes ALTER COLUMN unit_id TYPE UUID USING NULL::uuid")
    op.execute("ALTER TABLE user_notes ALTER COLUMN lesson_id DROP DEFAULT")
    op.execute(
        "ALTER TABLE user_notes ALTER COLUMN lesson_id TYPE UUID USING NULL::uuid"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_notes", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("user_notes_lesson_id_fkey"), "lessons", ["lesson_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("user_notes_unit_id_fkey"), "units", ["unit_id"], ["id"]
        )
        batch_op.alter_column(
            "lesson_id",
            existing_type=sa.Uuid(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "unit_id",
            existing_type=sa.Uuid(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("user_flashcards", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("user_flashcards_lesson_id_fkey"),
            "lessons",
            ["lesson_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("user_flashcards_unit_id_fkey"), "units", ["unit_id"], ["id"]
        )
        batch_op.alter_column(
            "lesson_id",
            existing_type=sa.Uuid(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "unit_id",
            existing_type=sa.Uuid(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=False
        )

    with op.batch_alter_table("lp_graph_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_target_node_id"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_source_node_id"))
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_target"), ["target_node_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_source"), ["source_node_id"], unique=False
        )

    with op.batch_alter_table("lp_documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "metadata_json",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "nodes_json",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("nodes")
        batch_op.drop_column("metadata")

    with op.batch_alter_table("lp_concept_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_target_concept_id"))
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_source_concept_id"))
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_target"),
            ["target_concept_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_source"),
            ["source_concept_id"],
            unique=False,
        )

    with op.batch_alter_table("lp_book_process", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_book_process_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_book_process_document_id"), ["document_id"], unique=False
        )

    with op.batch_alter_table("course_templates", schema=None) as batch_op:
        batch_op.alter_column(
            "structure",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        )

    # ### end Alembic commands ###
