"""initial schema (squashed baseline)

The historical migration chain was collapsed into this single baseline.
All tables, columns and indexes reflect the current SQLAlchemy models at
head ``b6c7d8e9f0a1``.  The revision id matches the previous head so
databases already migrated to head remain consistent.

Revision ID: b6c7d8e9f0a1
Revises:
Create Date: 2026-08-06 08:54:37.746862

"""

import sys
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Ensure learning_platform src is importable
_lp_src = str(
    Path(__file__).resolve().parent.parent.parent / "learning_platform" / "src"
)
if _lp_src not in sys.path:
    sys.path.insert(0, _lp_src)

from learning_platform.infrastructure.persistence.models.base import JsonType  # noqa: E402

# revision identifiers, used by Alembic.
revision: str = "b6c7d8e9f0a1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lp_book_process",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lp_document_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("image_format", sa.String(length=16), nullable=False),
        sa.Column("image_data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_document_images", schema=None) as batch_op:
        batch_op.create_index(
            "ix_lp_document_images_document_id", ["document_id"], unique=False
        )
        batch_op.create_index(
            "ix_lp_document_images_node_id", ["node_id"], unique=False
        )

    op.create_table(
        "lp_document_process",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("abs_path", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("run_mode", sa.String(length=16), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("last_completed_stage", sa.String(length=64), nullable=True),
        sa.Column("failed_stage", sa.String(length=64), nullable=True),
        sa.Column("resume_state", JsonType(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_document_process", schema=None) as batch_op:
        batch_op.create_index(
            "uq_lp_document_process_active_abs_path",
            ["abs_path"],
            unique=True,
            postgresql_where=sa.text("status IN ('pending','processing')"),
            sqlite_where=sa.text("status IN ('pending','processing')"),
        )

    op.create_table(
        "lp_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("owner_sub", sa.String(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.Column("nodes", JsonType(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_documents_owner_sub"), ["owner_sub"], unique=False
        )

    op.create_table(
        "lp_roll_back_agent_action",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("target_key", sa.String(length=64), nullable=False),
        sa.Column("precheck_passed", sa.Boolean(), nullable=False),
        sa.Column("target_summary", JsonType(), nullable=True),
        sa.Column("undo_steps", JsonType(), nullable=True),
        sa.Column("integrity_hash", sa.String(length=64), nullable=False),
        sa.Column("affected_row_count", sa.Integer(), nullable=False),
        sa.Column("affected_file_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_roll_back_agent_action", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lp_roll_back_agent_action_action_type", ["action_type"], unique=False
        )
        batch_op.create_index(
            "idx_lp_roll_back_agent_action_created_at", ["created_at"], unique=False
        )
        batch_op.create_index(
            "idx_lp_roll_back_agent_action_status", ["status"], unique=False
        )
        batch_op.create_index(
            "uq_lp_roll_back_agent_action_prepared_target_key",
            ["target_key"],
            unique=True,
            postgresql_where=sa.text("status = 'prepared'"),
            sqlite_where=sa.text("status = 'prepared'"),
        )

    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "triage_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_kind", sa.String(length=32), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=True),
        sa.Column("report_id", sa.String(length=128), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("triage_runs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_triage_runs_created_at", ["created_at"], unique=False
        )
        batch_op.create_index("idx_triage_runs_scope", ["scope_kind"], unique=False)
        batch_op.create_index("idx_triage_runs_status", ["status"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("google_id", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("picture_url", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_id"),
    )
    op.create_table(
        "course_templates",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("structure", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("course_id"),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("number_of_credits", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "flashcards",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("state", sa.Integer(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("elapsed_days", sa.Integer(), nullable=False),
        sa.Column("scheduled_days", sa.Integer(), nullable=False),
        sa.Column("due", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("card_id"),
    )
    op.create_table(
        "lp_annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("detector", sa.String(length=128), nullable=False),
        sa.Column("payload", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_annotations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_annotations_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_annotations_node_id"), ["node_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_annotations_type"), ["type"], unique=False
        )

    op.create_table(
        "lp_book_chapter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_book_chapter", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_book_chapter_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_book_chapter_unit_id"), ["unit_id"], unique=False
        )

    op.create_table(
        "lp_concepts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("aliases", JsonType(), nullable=True),
        sa.Column("source_node_ids", JsonType(), nullable=True),
        sa.Column("source_unit_ids", JsonType(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_concepts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_concepts_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_concepts_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lp_concepts_name"), ["name"], unique=False)

    op.create_table(
        "lp_knowledge_graphs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_knowledge_graphs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_knowledge_graphs_document_id"),
            ["document_id"],
            unique=False,
        )

    op.create_table(
        "lp_learning_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("unit_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("estimated_study_time_minutes", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("learning_objectives", JsonType(), nullable=True),
        sa.Column("content_references", JsonType(), nullable=True),
        sa.Column("definitions", JsonType(), nullable=True),
        sa.Column("examples", JsonType(), nullable=True),
        sa.Column("figures", JsonType(), nullable=True),
        sa.Column("tables", JsonType(), nullable=True),
        sa.Column("equations", JsonType(), nullable=True),
        sa.Column("exercises", JsonType(), nullable=True),
        sa.Column("source_node_ids", JsonType(), nullable=True),
        sa.Column("children_ids", JsonType(), nullable=True),
        sa.Column("prerequisite_ids", JsonType(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["lp_learning_units.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_learning_units", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_learning_units_document_id"),
            ["document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_learning_units_parent_id"), ["parent_id"], unique=False
        )

    op.create_table(
        "lp_pipeline_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("stage", sa.String(length=128), nullable=False),
        sa.Column("output", sa.String(length=1024), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("document_process_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_process_id"],
            ["lp_document_process.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_pipeline_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_pipeline_logs_document_process_id"),
            ["document_process_id"],
            unique=False,
        )

    op.create_table(
        "lp_reviewer_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requested_lp_documents_id", sa.Uuid(), nullable=False),
        sa.Column("resolved_lp_documents_id", sa.Uuid(), nullable=False),
        sa.Column("resolved_document_name", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("aggregate_verdict", sa.String(length=32), nullable=True),
        sa.Column("aggregate_summary", sa.Text(), nullable=False),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolved_lp_documents_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_reviewer_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_reviewer_run_requested_lp_documents_id"),
            ["requested_lp_documents_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_reviewer_run_resolved_lp_documents_id"),
            ["resolved_lp_documents_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_reviewer_run_status"), ["status"], unique=False
        )

    op.create_table(
        "lp_study_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=False),
        sa.Column("total_estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("total_lessons", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_study_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_study_plans_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student_progress",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("continuous_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("student_id", "node_id"),
    )
    op.create_table(
        "triage_findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("affected_count", sa.Integer(), nullable=False),
        sa.Column("sample_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["triage_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("triage_findings", schema=None) as batch_op:
        batch_op.create_index("idx_triage_findings_run_id", ["run_id"], unique=False)
        batch_op.create_index(
            "idx_triage_findings_severity", ["severity"], unique=False
        )
        batch_op.create_index("idx_triage_findings_table", ["table_name"], unique=False)

    op.create_table(
        "user_flashcards_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_flashcards_request", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_flashcards_request_scope_target",
            ["scope", "target_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_user_flashcards_request_user_id", ["user_id"], unique=False
        )
        batch_op.create_index(
            "uq_user_flashcards_request_active",
            ["scope", "target_id"],
            unique=True,
            postgresql_where=sa.text("status IN ('pending', 'in_progress')"),
        )

    op.create_table(
        "user_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("lesson_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_notes", schema=None) as batch_op:
        batch_op.create_index("idx_user_notes_lesson_id", ["lesson_id"], unique=False)
        batch_op.create_index("idx_user_notes_unit_id", ["unit_id"], unique=False)
        batch_op.create_index("idx_user_notes_user_id", ["user_id"], unique=False)

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "course_documents",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "document_id"),
    )
    op.create_table(
        "course_enrollments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("enrolled_at", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "course_id", name="uq_enrollment_user_course"),
    )
    op.create_table(
        "lp_book_lesson",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chapter_id"], ["lp_book_chapter.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_book_lesson", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_book_lesson_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_book_lesson_unit_id"), ["unit_id"], unique=False
        )

    op.create_table(
        "lp_concept_relationships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("source_concept_id", sa.Uuid(), nullable=False),
        sa.Column("target_concept_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_concept_id"], ["lp_concepts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_concept_id"], ["lp_concepts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_concept_relationships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_document_id"),
            ["document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_relation_type"),
            ["relation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_source_concept_id"),
            ["source_concept_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_concept_relationships_target_concept_id"),
            ["target_concept_id"],
            unique=False,
        )

    op.create_table(
        "lp_graph_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("graph_id", sa.Uuid(), nullable=False),
        sa.Column("node_type", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("concept_id", sa.Uuid(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"], ["lp_concepts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["graph_id"], ["lp_knowledge_graphs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["lp_learning_units.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_graph_nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_graph_nodes_concept_id"), ["concept_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_nodes_graph_id"), ["graph_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_nodes_node_type"), ["node_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_nodes_unit_id"), ["unit_id"], unique=False
        )

    op.create_table(
        "lp_milestones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_plan_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("lesson_ids", JsonType(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_plan_id"], ["lp_study_plans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_milestones", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_milestones_study_plan_id"),
            ["study_plan_id"],
            unique=False,
        )

    op.create_table(
        "lp_reviewer_page_result",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reviewer_run_id", sa.Uuid(), nullable=False),
        sa.Column("lp_documents_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("review_status", sa.String(length=64), nullable=False),
        sa.Column("review_error", sa.Text(), nullable=True),
        sa.Column("extracted_text_char_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("strengths", JsonType(), nullable=True),
        sa.Column("issues", JsonType(), nullable=True),
        sa.Column("recommendations", JsonType(), nullable=True),
        sa.Column("verdict", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lp_documents_id"], ["lp_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_run_id"], ["lp_reviewer_run.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_reviewer_page_result", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_reviewer_page_result_lp_documents_id"),
            ["lp_documents_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_reviewer_page_result_review_status"),
            ["review_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_reviewer_page_result_reviewer_run_id"),
            ["reviewer_run_id"],
            unique=False,
        )

    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.create_index("idx_units_course_id", ["course_id"], unique=False)

    op.create_table(
        "user_flashcards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("lesson_id", sa.Uuid(), nullable=True),
        sa.Column("is_generated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_flashcards", schema=None) as batch_op:
        batch_op.create_index(
            "idx_user_flashcards_course_id", ["course_id"], unique=False
        )
        batch_op.create_index(
            "idx_user_flashcards_created_by", ["created_by"], unique=False
        )
        batch_op.create_index(
            "idx_user_flashcards_lesson_id", ["lesson_id"], unique=False
        )
        batch_op.create_index("idx_user_flashcards_unit_id", ["unit_id"], unique=False)
        batch_op.create_index("idx_user_flashcards_user_id", ["user_id"], unique=False)

    op.create_table(
        "item_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["course_enrollments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("item_progress", schema=None) as batch_op:
        batch_op.create_index(
            "idx_item_progress_enrollment_id", ["enrollment_id"], unique=False
        )
        batch_op.create_index("idx_item_progress_item_id", ["item_id"], unique=False)

    op.create_table(
        "lp_book_page",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lp_book_lesson.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_book_page", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_book_page_lesson_id"), ["lesson_id"], unique=False
        )

    op.create_table(
        "lp_checkpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_plan_id", sa.Uuid(), nullable=False),
        sa.Column("milestone_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("checkpoint_type", sa.String(length=32), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("lesson_ids", JsonType(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["milestone_id"], ["lp_milestones.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["study_plan_id"], ["lp_study_plans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_checkpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_checkpoints_milestone_id"), ["milestone_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_checkpoints_study_plan_id"),
            ["study_plan_id"],
            unique=False,
        )

    op.create_table(
        "lp_graph_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("graph_id", sa.Uuid(), nullable=False),
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("target_node_id", sa.Uuid(), nullable=False),
        sa.Column("edge_type", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["graph_id"], ["lp_knowledge_graphs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"], ["lp_graph_nodes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"], ["lp_graph_nodes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_graph_edges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_edge_type"), ["edge_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_graph_id"), ["graph_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_source_node_id"),
            ["source_node_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lp_graph_edges_target_node_id"),
            ["target_node_id"],
            unique=False,
        )

    op.create_table(
        "lp_lessons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_plan_id", sa.Uuid(), nullable=False),
        sa.Column("milestone_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=False),
        sa.Column("lesson_type", sa.String(length=32), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("learning_objectives", JsonType(), nullable=True),
        sa.Column("prerequisites", JsonType(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["milestone_id"], ["lp_milestones.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["study_plan_id"], ["lp_study_plans.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["lp_learning_units.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_lessons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_lessons_milestone_id"), ["milestone_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_lessons_study_plan_id"), ["study_plan_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lp_lessons_unit_id"), ["unit_id"], unique=False
        )

    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.create_index("idx_sections_unit_id", ["unit_id"], unique=False)

    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("plan_lesson_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lessons_section_id", ["section_id", "display_order"], unique=False
        )

    op.create_table(
        "lp_book_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("content", JsonType(), nullable=True),
        sa.Column("bbox", JsonType(), nullable=True),
        sa.Column("style", JsonType(), nullable=True),
        sa.Column("metadata", JsonType(), nullable=True),
        sa.ForeignKeyConstraint(["page_id"], ["lp_book_page.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lp_book_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lp_book_item_page_id"), ["page_id"], unique=False
        )

    op.create_table(
        "practices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("required_correct", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("practice_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("practices", schema=None) as batch_op:
        batch_op.create_index(
            "idx_practices_section_id", ["section_id", "display_order"], unique=False
        )

    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.create_index("idx_quizzes_section_id", ["section_id"], unique=False)

    op.create_table(
        "section_unlock_overrides",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("unlocked_by", sa.Integer(), nullable=True),
        sa.Column("unlocked_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unlocked_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "section_id"),
    )
    op.create_table(
        "user_lesson_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("last_accessed_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "lesson_id"),
    )
    op.create_table(
        "user_practice_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("practice_id", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("best_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "practice_id"),
    )
    op.create_table(
        "user_quiz_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "quiz_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_quiz_progress")
    op.drop_table("user_practice_progress")
    op.drop_table("user_lesson_progress")
    op.drop_table("section_unlock_overrides")
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.drop_index("idx_quizzes_section_id")

    op.drop_table("quizzes")
    with op.batch_alter_table("practices", schema=None) as batch_op:
        batch_op.drop_index("idx_practices_section_id")

    op.drop_table("practices")
    with op.batch_alter_table("lp_book_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_book_item_page_id"))

    op.drop_table("lp_book_item")
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_index("idx_lessons_section_id")

    op.drop_table("lessons")
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.drop_index("idx_sections_unit_id")

    op.drop_table("sections")
    with op.batch_alter_table("lp_lessons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_lessons_unit_id"))
        batch_op.drop_index(batch_op.f("ix_lp_lessons_study_plan_id"))
        batch_op.drop_index(batch_op.f("ix_lp_lessons_milestone_id"))

    op.drop_table("lp_lessons")
    with op.batch_alter_table("lp_graph_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_target_node_id"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_source_node_id"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_graph_id"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_edges_edge_type"))

    op.drop_table("lp_graph_edges")
    with op.batch_alter_table("lp_checkpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_checkpoints_study_plan_id"))
        batch_op.drop_index(batch_op.f("ix_lp_checkpoints_milestone_id"))

    op.drop_table("lp_checkpoints")
    with op.batch_alter_table("lp_book_page", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_book_page_lesson_id"))

    op.drop_table("lp_book_page")
    with op.batch_alter_table("item_progress", schema=None) as batch_op:
        batch_op.drop_index("idx_item_progress_item_id")
        batch_op.drop_index("idx_item_progress_enrollment_id")

    op.drop_table("item_progress")
    with op.batch_alter_table("user_flashcards", schema=None) as batch_op:
        batch_op.drop_index("idx_user_flashcards_user_id")
        batch_op.drop_index("idx_user_flashcards_unit_id")
        batch_op.drop_index("idx_user_flashcards_lesson_id")
        batch_op.drop_index("idx_user_flashcards_created_by")
        batch_op.drop_index("idx_user_flashcards_course_id")

    op.drop_table("user_flashcards")
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.drop_index("idx_units_course_id")

    op.drop_table("units")
    with op.batch_alter_table("lp_reviewer_page_result", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_reviewer_page_result_reviewer_run_id"))
        batch_op.drop_index(batch_op.f("ix_lp_reviewer_page_result_review_status"))
        batch_op.drop_index(batch_op.f("ix_lp_reviewer_page_result_lp_documents_id"))

    op.drop_table("lp_reviewer_page_result")
    with op.batch_alter_table("lp_milestones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_milestones_study_plan_id"))

    op.drop_table("lp_milestones")
    with op.batch_alter_table("lp_graph_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_graph_nodes_unit_id"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_nodes_node_type"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_nodes_graph_id"))
        batch_op.drop_index(batch_op.f("ix_lp_graph_nodes_concept_id"))

    op.drop_table("lp_graph_nodes")
    with op.batch_alter_table("lp_concept_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_target_concept_id"))
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_source_concept_id"))
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_relation_type"))
        batch_op.drop_index(batch_op.f("ix_lp_concept_relationships_document_id"))

    op.drop_table("lp_concept_relationships")
    with op.batch_alter_table("lp_book_lesson", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_book_lesson_unit_id"))
        batch_op.drop_index(batch_op.f("ix_lp_book_lesson_chapter_id"))

    op.drop_table("lp_book_lesson")
    op.drop_table("course_enrollments")
    op.drop_table("course_documents")
    op.drop_table("user_roles")
    with op.batch_alter_table("user_notes", schema=None) as batch_op:
        batch_op.drop_index("idx_user_notes_user_id")
        batch_op.drop_index("idx_user_notes_unit_id")
        batch_op.drop_index("idx_user_notes_lesson_id")

    op.drop_table("user_notes")
    with op.batch_alter_table("user_flashcards_request", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_user_flashcards_request_active",
            postgresql_where=sa.text("status IN ('pending', 'in_progress')"),
        )
        batch_op.drop_index("ix_user_flashcards_request_user_id")
        batch_op.drop_index("ix_user_flashcards_request_scope_target")

    op.drop_table("user_flashcards_request")
    with op.batch_alter_table("triage_findings", schema=None) as batch_op:
        batch_op.drop_index("idx_triage_findings_table")
        batch_op.drop_index("idx_triage_findings_severity")
        batch_op.drop_index("idx_triage_findings_run_id")

    op.drop_table("triage_findings")
    op.drop_table("student_progress")
    op.drop_table("sessions")
    op.drop_table("role_permissions")
    with op.batch_alter_table("lp_study_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_study_plans_document_id"))

    op.drop_table("lp_study_plans")
    with op.batch_alter_table("lp_reviewer_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_reviewer_run_status"))
        batch_op.drop_index(batch_op.f("ix_lp_reviewer_run_resolved_lp_documents_id"))
        batch_op.drop_index(batch_op.f("ix_lp_reviewer_run_requested_lp_documents_id"))

    op.drop_table("lp_reviewer_run")
    with op.batch_alter_table("lp_pipeline_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_pipeline_logs_document_process_id"))

    op.drop_table("lp_pipeline_logs")
    with op.batch_alter_table("lp_learning_units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_learning_units_parent_id"))
        batch_op.drop_index(batch_op.f("ix_lp_learning_units_document_id"))

    op.drop_table("lp_learning_units")
    with op.batch_alter_table("lp_knowledge_graphs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_knowledge_graphs_document_id"))

    op.drop_table("lp_knowledge_graphs")
    with op.batch_alter_table("lp_concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_concepts_name"))
        batch_op.drop_index(batch_op.f("ix_lp_concepts_document_id"))
        batch_op.drop_index(batch_op.f("ix_lp_concepts_category"))

    op.drop_table("lp_concepts")
    with op.batch_alter_table("lp_book_chapter", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_book_chapter_unit_id"))
        batch_op.drop_index(batch_op.f("ix_lp_book_chapter_document_id"))

    op.drop_table("lp_book_chapter")
    with op.batch_alter_table("lp_annotations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_annotations_type"))
        batch_op.drop_index(batch_op.f("ix_lp_annotations_node_id"))
        batch_op.drop_index(batch_op.f("ix_lp_annotations_document_id"))

    op.drop_table("lp_annotations")
    op.drop_table("flashcards")
    op.drop_table("courses")
    op.drop_table("course_templates")
    op.drop_table("users")
    with op.batch_alter_table("triage_runs", schema=None) as batch_op:
        batch_op.drop_index("idx_triage_runs_status")
        batch_op.drop_index("idx_triage_runs_scope")
        batch_op.drop_index("idx_triage_runs_created_at")

    op.drop_table("triage_runs")
    op.drop_table("roles")
    op.drop_table("permissions")
    with op.batch_alter_table("lp_roll_back_agent_action", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_lp_roll_back_agent_action_prepared_target_key",
            postgresql_where=sa.text("status = 'prepared'"),
            sqlite_where=sa.text("status = 'prepared'"),
        )
        batch_op.drop_index("idx_lp_roll_back_agent_action_status")
        batch_op.drop_index("idx_lp_roll_back_agent_action_created_at")
        batch_op.drop_index("idx_lp_roll_back_agent_action_action_type")

    op.drop_table("lp_roll_back_agent_action")
    with op.batch_alter_table("lp_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lp_documents_owner_sub"))

    op.drop_table("lp_documents")
    with op.batch_alter_table("lp_document_process", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_lp_document_process_active_abs_path",
            postgresql_where=sa.text("status IN ('pending','processing')"),
            sqlite_where=sa.text("status IN ('pending','processing')"),
        )

    op.drop_table("lp_document_process")
    with op.batch_alter_table("lp_document_images", schema=None) as batch_op:
        batch_op.drop_index("ix_lp_document_images_node_id")
        batch_op.drop_index("ix_lp_document_images_document_id")

    op.drop_table("lp_document_images")
    op.drop_table("lp_book_process")
    op.drop_table("documents")
    # ### end Alembic commands ###
