"""Agentic operations primitives for deterministic triage."""

from __future__ import annotations

from learning_platform.agentic_ops.contracts.mcp import (
    CancelAgentActionRequest,
    CanceledAgentActionResult,
    ColumnNullStat,
    DatabaseEntriesReportPage,
    ExecutedAgentActionResult,
    ExecuteDeleteDocumentProcessRunsRequest,
    ForeignKeyGap,
    ManagedDocumentEntry,
    MissingEntryTable,
    PreparedAgentActionResult,
    PrepareDeleteDocumentProcessRunsRequest,
    ReportScope,
    RollBackAgentActionRequest,
    RolledBackAgentActionResult,
    SliceDocumentPagesRequest,
    SliceDocumentPagesResult,
    TableEntryRow,
    TableReport,
)
from learning_platform.agentic_ops.mcp.client import (
    McpActionClient,
    McpClientError,
    McpReportClient,
    extract_mcp_payload,
    parse_tool_result_payload,
)
from learning_platform.agentic_ops.mcp_server import (
    MCP_ACTION_SERVER_NAME,
    MCP_REPORT_SERVER_NAME,
    MCP_SERVER_NAME,
    STREAMABLE_HTTP_ACTION_PATH,
    STREAMABLE_HTTP_PATH,
    STREAMABLE_HTTP_REPORT_PATH,
    create_action_mcp_server,
    create_mcp_server,
    create_report_mcp_server,
    run_stdio_action_server,
    run_stdio_report_server,
    run_stdio_server,
    run_streamable_http_action_server,
    run_streamable_http_report_server,
    run_streamable_http_server,
)
from learning_platform.agentic_ops.rules.defaults import build_default_rule_set
from learning_platform.agentic_ops.rules.models import (
    CrossTableMinimumRule,
    ForeignKeyIntegrityRule,
    RequiredColumnsRule,
    RuleSet,
    TableNonEmptyRule,
    TriageRule,
)
from learning_platform.agentic_ops.settings import AgenticOpsSettings
from learning_platform.agentic_ops.triage.agent import ReportProvider, TriageAgent
from learning_platform.agentic_ops.triage.models import (
    TriageFinding,
    TriageResult,
    TriageStats,
    TriageVerdict,
)
from learning_platform.agentic_ops.triage.service import TriageService

__all__ = [
    "AgenticOpsSettings",
    "CancelAgentActionRequest",
    "CanceledAgentActionResult",
    "ColumnNullStat",
    "CrossTableMinimumRule",
    "DatabaseEntriesReportPage",
    "ExecuteDeleteDocumentProcessRunsRequest",
    "ExecutedAgentActionResult",
    "ForeignKeyGap",
    "ForeignKeyIntegrityRule",
    "extract_mcp_payload",
    "McpActionClient",
    "McpClientError",
    "McpReportClient",
    "MCP_ACTION_SERVER_NAME",
    "MCP_SERVER_NAME",
    "MCP_REPORT_SERVER_NAME",
    "ManagedDocumentEntry",
    "MissingEntryTable",
    "PrepareDeleteDocumentProcessRunsRequest",
    "PreparedAgentActionResult",
    "ReportProvider",
    "ReportScope",
    "RequiredColumnsRule",
    "RollBackAgentActionRequest",
    "RolledBackAgentActionResult",
    "SliceDocumentPagesRequest",
    "SliceDocumentPagesResult",
    "RuleSet",
    "STREAMABLE_HTTP_ACTION_PATH",
    "STREAMABLE_HTTP_PATH",
    "STREAMABLE_HTTP_REPORT_PATH",
    "TableEntryRow",
    "TableNonEmptyRule",
    "TableReport",
    "TriageAgent",
    "TriageFinding",
    "TriageResult",
    "TriageService",
    "TriageRule",
    "TriageStats",
    "TriageVerdict",
    "build_default_rule_set",
    "create_action_mcp_server",
    "create_mcp_server",
    "create_report_mcp_server",
    "parse_tool_result_payload",
    "run_stdio_action_server",
    "run_stdio_report_server",
    "run_stdio_server",
    "run_streamable_http_action_server",
    "run_streamable_http_report_server",
    "run_streamable_http_server",
]
